import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Sidebar from "@/Component/Sidebar";

const inter = Inter({
    variable: "--font-sans",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Admin Panel - DataProcessing",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={`${inter.variable} antialiased flex`}>
                <Sidebar/>
                {/* Main Content */}
                <main className="ml-[10vw] w-[90vw] min-h-screen">
                    {children}
                </main>

                <Toaster position="top-center" reverseOrder={false} />
            </body>
        </html>
    );
}
